package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	if len(os.Args) == 1 {
		fmt.Println("example: go-embed x.txt x.exe x.html")
		return
	}

	out := bytes.NewBufferString("// Code generated by go-embed.\npackage main\n\n")
	for _, arg := range os.Args[1:] {
		if r := convert(arg); r != "" {
			out.WriteString(r + "\n\n")
		}
	}

	_ = ioutil.WriteFile("embed.go", out.Bytes(), 0777)
}

// convert file as:
// var _xxxDll = []byte("\x4d\x5a...")
func convert(file string) string {
	var buf bytes.Buffer
	filename := filepath.Base(file)
	bn := strings.ToLower(filename)

	if strings.HasPrefix(bn, ".") {
		return ""
	}
	if strings.HasSuffix(bn, ".") {
		bn = strings.TrimRight(bn, ".")
	}

	n := strings.Index(bn, ".")
	if n != -1 {
		ext := filepath.Ext(bn)
		ext = strings.Trim(ext, ".")
		bn = bn[:n] + strings.Title(ext)
	}
	bn = "_" + bn

	_, _ = fmt.Fprintf(&buf, "// %s from %s\nvar %s = []byte(\"", bn, filename, bn)
	data, err := ioutil.ReadFile(file)
	if err != nil {
		panic(err)
	}

	for n, i := len(data), 0; i < n; i++ {
		_, _ = fmt.Fprintf(&buf, "\\x%02x", data[i])
	}
	_, _ = buf.WriteString(`")`)
	return buf.String()
}
